---
- defaults:
    link:
      create: true
      relink: true

- shell:
    - [rm ~/.profile ~/.bashrc ~/.bash_logout, Removing default bash files]

- create:
    - ~/.gnupg
    - ~/.local/share
    - ~/.local/state
    - ~/.config
    - ~/.cache

- clean: ["~", "~/.gnupg", "~/.local/bin"]
- clean:
    ~/.config:
      recursive: true

- link:
    # EditorConfig
    ~/.editorconfig:
    # Bash
    ~/.profile:
    ~/.bashrc:
    ~/.bash_logout:
    # Z shell
    ~/.zshenv:
    # User
    ~/.aliases:
    ~/.config/:
      glob: true
      path: config/*
    ~/.gnupg/:
      glob: true
      path: gnupg/*
    ~/.local/bin/:
      glob: true
      path: local/bin/*

- shell:
    - [source ~/.profile, Sourcing .profile]

- sudo:
    - apt:
        # Security
        - apt-show-versions
        - apt-transport-https
        - debsums
        - unattended-upgrades
        # Tooling, Settings
        - curl
        - fish
        - jq
        - zsh
        # Programming
        - cargo
        - git
        - git-lfs
        - golang-go
        - lua5.4
        - neovim
        - pandoc
        - python3-jedi
        - python3-pip
        - ruby-full  # Install first
        - rbenv
        - shellcheck
        - tmux
        - yamllint
        # Other
        - newsboat

# TODO add a check for presence before install. Plugin uses `--force` which make
# the execution unnecessary long
# - cargo:
#     - cargo-update
#     - du-dust
#     - fd-find
#     - git-delta
#     - navi
#     - ripgrep

- go:
    # - github.com/jacobbednarz/go-csp-collector@latest
    - mvdan.cc/sh/v3/cmd/shfmt@latest

- pip:
    file: requirements.txt
    user: true # Like --user

- shell:
    - [python3 -m pipx ensurepath, Ensure pipx path]

- create:
    - ~/Development/src/github.com/mawww/kakoune

- git:
    "~/Development/src/github.com/mawww/kakoune":
      url: https://github.com/mawww/kakoune.git
      description: "kakoune - mawww's experiment for a better code editor"
