---
- shell:
    - [sleep 8, Sleeping to release apt...]

- sudo:
    - apt:
        # TODO: separate profile into CLI only and GUI
        # Tooling, Settings
        - conky-all
        # - fonts-ibm-plex
        - fonts-noto-cjk
        - fonts-noto-cjk-extra
        - fonts-noto-color-emoji
        # - fish
        - ibus-mozc
        - mpv
        # - snapd
        - webext-ublock-origin-firefox
        # Security/Privacy
        - bleachbit
        # - clamav
        # - clamav-daemon
        # - privoxy
        # Programming
        - alacritty
        # - github-desktop
        - mozc-utils-gui
        # - ruby-full  # Install first
        # - rbenv
        - virt-manager # Install first
        - qemu-kvm
        - spice-vdagent
        # Other
        - cmus
        # - gimp
        # - gnome-shell-pomodoro
        # - steam
        # - newsboat
    - shell:
        - [
            cp --remove-destination etc/privoxy/default.action /etc/privoxy/default.action,
            Copying privoxy config file,
          ]
        - [
            cp --remove-destination etc/privoxy/config /etc/privoxy/config,
            Copying privoxy config file,
          ]
        - [
            cp --remove-destination etc/privoxy/user.action /etc/privoxy/user.action,
            Copying privoxy config file,
          ]
        - [
            cp --remove-destination etc/ssh/ssh_config.d/default.conf /etc/ssh/ssh_config.d/default.conf,
            Copying privoxy config file,
          ]
        - [
            cp --remove-destination etc/dnscrypt-proxy/blocklists.txt /etc/dnscrypt-proxy/blocklists.txt,
            Copying DNScrypt-proxy blocklists,
          ]
        - [
            cp --remove-destination etc/dnscrypt-proxy/dnscrypt-proxy.toml /etc/dnscrypt-proxy/dnscrypt-proxy.toml,
            Copying DNScrypt-proxy config file,
          ]

- flatpak:
    # - com.calibre_ebook.calibre
    # - com.discordapp.Discord
    - com.github.tchx84.Flatseal
    - com.vscodium.codium
    # - io.lmms.LMMS
    # - net.xmind.XMind
    # - org.kde.digikam
    - org.keepassxc.KeePassXC
    # - org.musicbrainz.Picard
    - org.signal.Signal
    - org.standardnotes.standardnotes
    # - us.zoom.Zoom

- cargo:
    - doh-proxy
#     - du-dust

- go:
    # - github.com/karan/fleets@latest
    # - github.com/cointop-sh/cointop@latest
    # - github.com/Narasimha1997/fake-sms@latest
    - github.com/schachmat/wego@latest
    # - github.com/jacobbednarz/go-csp-collector@latest

- pipx:
    file: requirements-pipx.txt

- create:
    - ~/Development/src/github.com/StevenBlack/hosts

- git:
    "~/Development/src/github.com/StevenBlack/hosts":
      url: https://github.com/StevenBlack/hosts.git
      description: "hosts - Consolidating and extending hosts files from several well-curated sources."
