#!/usr/bin/env bash

# set -e

# Use with `./install mac work`

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
CONFIG_DIR="meta/configs"
DOTBOT_DIR="meta/dotbot"
DOTBOT_PLUGINS_DIR="meta/plugins/*"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --recursive
git submodule update --init --recursive
git submodule update --remote --merge

for conf in ${DEFAULT_CONFIG_PREFIX} "${@}"; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        --plugin-dir "$DOTBOT_PLUGINS_DIR" \
        --base-directory "${BASEDIR}" \
        --config-file "${CONFIG_DIR}/${conf}${CONFIG_SUFFIX}"
done
