##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################


##################################
#         Global settings        #
##################################

# Empty listen_addresses to use systemd socket activation
listen_addresses = []
#server_names = ['quad9-dnscrypt-ip4-filter-pri', 'cloudflare']
server_names = []
# Use servers reachable over IPv4
ipv4_servers = true
# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = true
# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true
# Use servers implementing the DNS-over-HTTP/2 protocol
#doh_servers = true
# Server must support DNS security extensions (DNSSEC)
require_dnssec = true
# Server must not log user queries (declarative)
require_nolog = true
# Server must not enforce its own blacklist (for parental control, ads blocking...)
#require_nofilter = true

# How long a DNS query will wait for a response, in milliseconds
#timeout = 2500

# Keepalive for HTTP (HTTPS, HTTP/2) queries, in seconds
#keepalive = 30

# DNSCrypt: Create a new, unique key for every single DNS query
# This may improve privacy but can also have a significant impact on CPU usage
# Only enable if you don't have a lot of network load
#dnscrypt_ephemeral_keys = false

# DoH: Disable TLS session tickets - increases privacy but also latency
#tls_disable_session_tickets = false


#########################
#        Filters        #
#########################

# Immediately respond to IPv6-related queries with an empty response
# This makes things faster when there is no IPv6 connectivity, but can
# also cause reliability issues with some stub resolvers.
# Do not enable if you added a validating resolver such as dnsmasq in front
# of the proxy.

block_ipv6 = false


##################################################################################
#        Route queries for specific domains to a dedicated set of servers        #
##################################################################################

## Example map entries (one entry per line):
## example.com 9.9.9.9
## example.net 9.9.9.9,8.8.8.8,1.1.1.1

forwarding_rules = 'forwarding-rules.txt'


###############################
#        Cloaking rules       #
###############################

# Cloaking returns a predefined address for a specific name.
# In addition to acting as a HOSTS file, it can also return the IP address
# of a different name. It will also do CNAME flattening.
#
# Example map entries (one entry per line)
# example.com     10.1.1.1
# www.google.com  forcesafesearch.google.com

#cloaking_rules = 'cloaking-rules.txt'


###########################
#        DNS cache        #
###########################

# Enable a DNS cache to reduce latency and outgoing traffic
cache = true

# Cache size
cache_size = 512

# Minimum TTL for cached entries
cache_min_ttl = 600

# Maximum TTL for cached entries
cache_max_ttl = 86400

# Minimum TTL for negatively cached entries
cache_neg_min_ttl = 60

# Maximum TTL for negatively cached entries
cache_neg_max_ttl = 600



##################################
#        Local DoH server        #
##################################

[local_doh]

## dnscrypt-proxy can act as a local DoH server. By doing so, web browsers
## requiring a direct connection to a DoH server in order to enable some
## features will enable these, without bypassing your DNS proxy.

## Addresses that the local DoH server should listen to

listen_addresses = ['127.0.0.1:3000']


## Path of the DoH URL. This is not a file, but the part after the hostname
## in the URL. By convention, `/dns-query` is frequently chosen.
## For each `listen_address` the complete URL to access the server will be:
## `https://<listen_address><path>` (ex: `https://127.0.0.1/dns-query`)

path = '/dns-query'


## Certificate file and key - Note that the certificate has to be trusted.
## See the documentation (wiki) for more information.

cert_file = 'localhost.pem'
cert_key_file = 'localhost.pem'



###############################
#        Query logging        #
###############################

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'


############################################
#        Suspicious queries logging        #
############################################

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'


######################################################
#        Pattern-based blocking (blacklists)         #
######################################################

[blacklist]
  # Path to the file of blocking rules (absolute, or relative to the same directory as the executable file)
  blacklist_file = 'blocklists.txt'



##########################################
#        Time access restrictions        #
##########################################

## One or more weekly schedules can be defined here.
## Patterns in the name-based blocked_names file can optionally be followed with @schedule_name
## to apply the pattern 'schedule_name' only when it matches a time range of that schedule.
##
## For example, the following rule in a blocklist file:
## *.youtube.* @time-to-sleep
## would block access to YouTube during the times defined by the 'time-to-sleep' schedule.
##
## {after='21:00', before= '7:00'} matches 0:00-7:00 and 21:00-0:00
## {after= '9:00', before='18:00'} matches 9:00-18:00

[schedules]

  # [schedules.'time-to-sleep']
  # mon = [{after='21:00', before='7:00'}]
  # tue = [{after='21:00', before='7:00'}]
  # wed = [{after='21:00', before='7:00'}]
  # thu = [{after='21:00', before='7:00'}]
  # fri = [{after='23:00', before='7:00'}]
  # sat = [{after='23:00', before='7:00'}]
  # sun = [{after='21:00', before='7:00'}]

  # [schedules.'work']
  # mon = [{after='9:00', before='18:00'}]
  # tue = [{after='9:00', before='18:00'}]
  # wed = [{after='9:00', before='18:00'}]
  # thu = [{after='9:00', before='18:00'}]
  # fri = [{after='9:00', before='17:00'}]

  [schedules.'work-time-to-sleep']
  mon = [{after='9:00', before='13:00'}, {after='14:00', before='18:00'}, {after='21:00', before='7:00'}]
  tue = [{after='9:00', before='13:00'}, {after='14:00', before='18:00'}, {after='21:00', before='7:00'}]
  wed = [{after='9:00', before='13:00'}, {after='14:00', before='18:00'}, {after='21:00', before='7:00'}]
  thu = [{after='9:00', before='13:00'}, {after='14:00', before='18:00'}, {after='21:00', before='7:00'}]
  fri = [{after='9:00', before='13:00'}, {after='14:00', before='17:00'}, {after='23:00', before='7:00'}]
  sat = [{after='23:00', before='7:00'}]
  sun = [{after='21:00', before='7:00'}]



#########################
#        Servers        #
#########################

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

